local Device = require("device")

return {
    shortcuts_fm = {
        modifier_plus_up                 = nil,
        modifier_plus_down               = nil,
        modifier_plus_left               = nil,
        modifier_plus_right              = nil,
        modifier_plus_left_page_forward  = nil,
        modifier_plus_left_page_back     = nil,
        modifier_plus_right_page_forward = nil,
        modifier_plus_right_page_back    = nil,
        modifier_plus_back               = {open_previous_document = true,},
        modifier_plus_home               = Device:hasWifiToggle() and {toggle_wifi = true,} or {},
        modifier_plus_press              = nil,
        -- alt
        alt_plus_up                 = nil,
        alt_plus_down               = nil,
        alt_plus_left               = nil,
        alt_plus_right              = nil,
        alt_plus_left_page_forward  = nil,
        alt_plus_left_page_back     = nil,
        alt_plus_right_page_forward = nil,
        alt_plus_right_page_back    = nil,
        alt_plus_back               = nil,
        alt_plus_home               = nil,
        alt_plus_press              = nil,
    },
    shortcuts_reader = {
        modifier_plus_up                 = {toc = true,},
        modifier_plus_down               = {book_map = true,},
        modifier_plus_left               = {bookmarks = true,},
        modifier_plus_right              = {toggle_bookmark = true,},
        modifier_plus_left_page_forward  = {next_location = true,},
        modifier_plus_left_page_back     = {previous_location = true,},
        modifier_plus_right_page_forward = {next_location = true,},
        modifier_plus_right_page_back    = {previous_location = true,},
        modifier_plus_back               = {open_previous_document = true,},
        modifier_plus_home               = Device:hasWifiToggle() and {toggle_wifi = true,} or {},
        modifier_plus_press              = {full_refresh = true,},
        --alt
        alt_plus_up                 = nil,
        alt_plus_down               = nil,
        alt_plus_left               = nil,
        alt_plus_right              = nil,
        alt_plus_left_page_forward  = nil,
        alt_plus_left_page_back     = nil,
        alt_plus_right_page_forward = nil,
        alt_plus_right_page_back    = nil,
        alt_plus_back               = nil,
        alt_plus_home               = nil,
        alt_plus_press              = nil,
    },
}
